== Issues




*@ISSUE {counter:task} 20180630* +
Zusätzlich Eigenschaft "readonly" hinzufügen, welche die Speicherung der Entitäten und
ihr zugewiesener Eigenschaften verhindert. Manche Schemata dienen nur der Beschreibung
einer schon existerenden Struktur.

*@ISSUE {counter:task} 20180630* +
Tiefe "depthLevel" setzen mit der die Abbruchstufe definiert wird, ab welcher
die Verarbeitung abbricht.



*@ISSUE {counter:task} 20180928* +
Wenn Änderungen am Datensatz passieren, bei denen sich die Beziehungen
zu anderen Objekte ändern. Dann müssen die vorigen Beziehungen gelöscht
werden (außer, die Revisionierung ist aktiviert).

*@ISSUE {counter:task} 20180928* +
Allgemeines Löschen implementieren.


*@ISSUE {counter:task} 20180928* +
MongoDB Implementierung: Schema(Indexing), Save, Find, Delete


*@ISSUE {counter:task} 20181030* +
Abfrage der Objekte implementieren mit:

* "Offset" und "limit"
* conditions
* sort


*@ISSUE {counter:task} 20201223* +
Als separates StorageRef mit eigenem Entitycontroller deinieren

*@ISSUE {counter:task} 20201223* +
Multiple Entitäten für eine Tabelle erlauben bzw. neuen Typ definieren

*@ISSUE {counter:task} 20201223* +
Join Bedingung über schon eingebundene Klasse bzw. ermöglicht Übergabe per string
oder Funktion. Zyklische imports prüfen.
```
@Property(
type: ModulVersion
)
versions: ModulVersion


@Property(
 join: Join(ModulVersion ...)
)
refOver: ModulVersionABC
```


